Add day 10 exercise 7
This code fails because the `String` class is final and so cannot be
modified:

    $ javac NewString.java
    NewString.java:1: error: cannot inherit from final String
    public class NewString extends String {
                                  ^
    1 error